name: Build & Deploy
on:
  push:
    branches:
      - "deploy/k8s"
jobs:
  build_and_deploy:
    name: Deploy infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - uses: docker://pulumi/actions
        with:
          args: up --yes
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
          PULUMI_ROOT: infra